name: Run Aerialist Default Tests
run-name: Run Aerialist Default Tests
on: workflow_dispatch

jobs:
    Run-Aerialist-Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2 
              
            - name: Build Test Bench Image
              uses: docker/build-push-action@v2
              with:
               tags: 'Dockerfile'
               push: false

            - name: Run Mission1 Test
              uses: addnab/docker-run-action@v3
              with:
                image: 'Dockerfile'
                run: python3 aerialist exec --test samples/tests/mission1.yaml
            
            - name: Run Manual1 Test
              uses: addnab/docker-run-action@v3
              with:
                image: 'Dockerfile'
                run: python3 aerialist exec --test samples/tests/manual1.yaml